In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import yfinance as yf


tickers = ["JNJ", "AAPL", "MSFT", "PG", "KO"]
start = "2017-01-01"
end = "2020-12-31"

stock_data = {}

/Users/negin/Library/Python/3.9/lib/python/site-packages/urllib3/__init__.py:35: NotOpenSSLWarning: urllib3 v2 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(

In [6]:
# Download market indext data for S&P 500 index ticker
sp500 = yf.download("^GSPC", start=start, end=end, auto_adjust=True, progress=False)
sp500.columns = sp500.columns.droplevel(1)
sp500_market_return = sp500['Close'].pct_change().to_frame(name='market_return')
sp500_market_return

            market_return
Date
2017-01-03            NaN
2017-01-04       0.005722
2017-01-05      -0.000771
2017-01-06       0.003517
2017-01-09      -0.003549
...                   ...
2020-12-23       0.000746
2020-12-24       0.003537
2020-12-28       0.008723
2020-12-29      -0.002227
2020-12-30       0.001342

[1006 rows x 1 columns]

In [7]:
# Download stock data for each ticker and store it in a dictionary
for ticker in tickers:
    stock_data[ticker] = yf.download(ticker, start=start, end=end, auto_adjust=True, progress=False)
    stock_data[ticker].columns = stock_data[ticker].columns.droplevel(1)
    stock_data[ticker] = stock_data[ticker].merge(sp500_market_return, left_index=True, right_index=True, how='inner')

stock_data['AAPL']

,Close,High,Low,Open,Volume,market_return
Date,,,,,,
2017-01-03,26.745855,26.787304,26.425780,26.665261,115127600,NaN
2017-01-04,26.715921,26.828755,26.653749,26.676776,84472400,0.005722
2017-01-05,26.851784,26.909351,26.667567,26.692897,88774400,-0.000771
2017-01-06,27.151133,27.208700,26.819543,26.890926,127007600,0.003517
2017-01-09,27.399822,27.501142,27.158040,27.160341,134247600,-0.003549
...,...,...,...,...,...,...
2020-12-23,127.364120,128.793744,127.189055,128.531168,88223700,0.000746
2020-12-24,128.346390,129.795483,127.500283,127.714243,54930100,0.003537
2020-12-28,132.936813,133.568960,129.844121,130.310952,124486200,0.008723
2020-12-29,131.166748,134.979111,130.651302,134.259440,121047300,-0.002227
2020-12-30,130.048340,132.256015,129.737119,131.857269,96452100,0.001342